CMake/External_Eigen.cmake
Patches/Eigen/Patch.cmake
Patches/Eigen/language_support.cmake

Patch Eigen to fix issues when using the ninja generator.
The current release fails when searching for a Fortran compiler when using ninja.
The patch was to add -G ${CMAKE_GENERATOR} to the COMMAND in execute_process. We would fail on ninja without it, since it would not consider the actual generator used.

Patch eigen ninja fortran fix

---

CMake/External_Qt.cmake

Works around QTBUG-28132 where multiple threads during install can see that a directory doesn't exist and try to make it which fails on windows.

Work around QTBUG-28132 Race Condition

---

CMakeLists.txt

This allows the user to turn everything on and the (now that ALL is
reset) turn off 1 or 2 packages -- a reasonble use case

Reset ENABLE_ALL_PACKAGES on Configure

---

CMake/External_OpenCV.cmake

Useful to disable CUDA in OpenCV on unsupported (but detected)
platforms

Add fletch_DISABLE_GPU_SUPPORT

---

CMake/fletch-tarballs.cmake

There was an issue in Eigen where it was incorrectly using C++11
features when the compiler did not support them (use of nullptr symbol).
The new version of Eigen has a revised macro that correctly defines
things such that those C++11 features are not used when not actually
supported.

Increased Eigen version from 3.2.7 -> 3.2.8

---

CMake/External_OpenCV.cmake

This commit defaults fletch to build OpenCV without the highgui
package. When highgui is enabled, OpenCV searches for ffmpeg, but
(at least on my mac) it finds the "system" (macport) include files
before its local ffmpeg, and fails to build. Turning highgui off
allows OpenCV to build.
As far as I know, no fletch clients require highgui... if this
changes, we can revisit with a more nuanced solution.

Add a fletch-level option for OpenCV's highgui; defaults to off.

---

CMake/External_OpenCV.cmake

MAP-Tk and the OpenCV plugin require highgui. Once we have ffmpeg in fletch,
we can probably remove this option.

Default to building OpenCV's highgui.

---

CMake/fletch-tarballs.cmake

The old version of VXL is broken in the way in installs some configured
vnl headers and causes errors building MAP-Tk.  Revert to a newer
version.
This reverts commit 14c5c6b8074bc52781fc6fbbe2fdecf0645250d1.

Revert "Latest version of VXL is not compatible with VidTK"

---

Patches/Boost/Patch.cmake
Patches/Boost/pthread/once.hpp
Patches/Boost/pthread/once_atomic.hpp

Boost fails to build on gcc >= 5.2. The following patch addresses the issue in its pthread related code, once and once_atomic.

Patch Boost build for gcc >= 5.2

---

CMake/fletch-tarballs.cmake
Patches/shapelib/Patch.cmake

The download location has moved.  Beta is no longer available.  The updated version does not seem to need the patch (the patch breaks the build)

Fix shapelib

---

CMake/External_Caffe.cmake

This patch is required for an update to latest CMake's Find_HDF5 module. CMake is attempting to do things correctly now, while Caffe is not. The better patch would be to the Caffe CMake code, but that is a much longer path before we have something we can use.

Fix the HDF5_libraries to Caffe.

---

Patches/OpenCV/OpenCVConfig.cmake
Patches/OpenCV/OpenCVDetectCXXCompiler.cmake
Patches/OpenCV/Patch.cmake

This patch back-ports the following upstream patch to allow OpenCV to build correctly with Visual Studio 2015
https://github.com/Itseez/opencv/commit/40b765b7c2de94b6535a4e9fd07780153e6badae

patch OpenCV to use VS2015

---

Patches/libtiff/CMakeLists.txt

On newer gcc, the linker versions the symbols and causes linker issues with packages that try to link libtiff.

Disable ld-version-script in libtiff.

---

Patches/OpenCV/Patch.cmake
Patches/OpenCV/graphcuts.cpp

This patch disables the CUDA graphcut feature that was supported in 7.5
but not 8.0.  This is the same patch applied to upstream OpenCV here:
https://github.com/opencv/opencv/pull/6510/files

Patch OpenCV to build against CUDA >= 8.0

---

CMake/External_Ceres.cmake
CMake/fletch-tarballs.cmake

Now that GLog is in Fletch, make Ceres use GLog if GLog was enabled.
I found that I was actually getting linking errors in MAP-Tk if GLog was being built in Fletch but not used in Ceres.  I'm not sure why, but this fixes it.  It's also the right thing to do since Ceres highly recommends using GLog when available.

Use glog in ceres

---

CMake/External_Ceres.cmake

A variable passed to CMake was missing a "-D" prefix causing the
variable to not be set in CMake correctly.

Fixed error in passing a CMake variable.

---

CMake/fletch-tarballs.cmake

When fletch_ENABLE_ALL_PACKAGES is set from the command line cmake, OpenCV doesn't fully configure because technically it isn't enabled yet when fletch-tarballs is included. Exand the OpenCV conditional to include fletch_ENABLE_ALL_PACKAGES so it will provide its defaults when only fletch_ENABLE_ALL_PACKAGES is selected.
This patch also sets the default OpenCV version to 3.

Configure OpenCV when fletch_ENABLE_ALL_PACKAGES is set on cli.

---

README.md

The link that was in this file did not work from github.  Github added github.com in front of the link. If you put http:: in the link it works from github.

Fix KWIVER link in readme file.

---

CMake/fletch-tarballs.cmake

This is the first version of Eigen with the fix for building with
ninja. This fixes the false error of an invalid version of ninja
from CMake.

Move to Eigen 3.2.9.

---

CMake/External_OpenCV.cmake

This branch removes the need to specifically enable FFmpeg in OpenCV. If both are enabled, the association is made.

If FFmpeg and OpenCV are enabled, link them.

---

Patches/Boost/Build.cmake
Patches/Boost/Configure.cmake

This are commits cherry-picked from @mattdawkins much larger viame/master branch that specifically address the problem of building Boost.Python on MacOS.

Fix boost python build

---

CMake/fletch-tarballs.cmake

Updated package info to use new VXL master (with fixed ffmpeg defines)

Update VXL URL and checksum for new master version

---

CMake/fletch-tarballs.cmake
CMakeLists.txt

ITK isn't actually being used, but takes up a significant amount of dashboard time when python is enabled. We don't want to get rid of ITK, so to compromise a flag was added to exclude it from fletch_ENABLE_ALL_PACKAGES.

Add experimental flag to avoid building ITK in dashboards

---

CMake/External_Ceres.cmake
CMake/External_VXL.cmake
CMake/External_libkml.cmake
CMake/External_log4cplus.cmake

This patch fixes numerous issues with the variables exported by Fletch and used by KWIVER to find the Fletch packages.
There are likely other missing variables and variable naming issues (e.g. name case) that need to be fixed, but these fixes are the ones needed to address current build issues, especially on Windows.

Fix FletchConfig.cmake package_DIR variables

---

CMake/External_Ceres.cmake
CMake/External_VXL.cmake
CMake/External_log4cplus.cmake

use all lower case, as that is the case used for its log4cplusConfig.cmake
Also, turn unicode off

Configure log4plus

---

CMake/fletch-tarballs.cmake

The filename is not actually part of the download URL. As is, fletch breaks when it comes time to build caffe.

Fix Caffe for Windows URL

---

CMake/External_Caffe.cmake
CMake/FindNumPy.cmake
CMakeLists.txt
Doc/release-notes/1.1.0.txt

When trying to build Caffe with fletch, it crashed on an error saying that it could not find numpy. I added an explicit find_package for NumPy and passed the python variables down to Caffe. This seems to fix the issue.
Side note: The FindNumpy script that I added is the same one used in Caffe. I find it odd that Caffe wasn't able to find it by itself considering its using the same script. My current guess it that it might have to do with the fact that I installed numpy to my python2 virtual environment.
(This is an updated version of PR #168 with correct branch naming conventions)

Add FindNumpy script for Caffe

---

CMake/fletch-tarballs.cmake
Doc/release-notes/1.1.0.txt

Upgrading the version of Ceres Solver seem to build fine in Fletch, but it still needs more testing in KWIVER before we merge.

Upgrade Ceres Solver

---

CMake/External_HDF5.cmake
CMake/External_Qt.cmake
Patches/HDF5/CMakeTests.cmake
Patches/HDF5/Patch.cmake
Patches/Qt/Patch.cmake
Patches/Qt/itemviews.cpp
Patches/Qt/previewmanager.cpp

Qt won't build with gcc 6. This patch is a bit heavy handed since it disables the scripts module. I don't believe we use it anywhere and I don't think this patch is a permanent need since we'll likely switch over to Qt 5 at some point.

Fix qt gcc 6

---

CMake/External_Ceres.cmake

This is to fix the dashboard error I've been having where Ceres is built before GFlags, and consequently GFlags can't be found.

Force GFlags to be built before Ceres

---

CMake/fletch-tarballs.cmake

We are using 1 archive to server all platforms, I switched to the windows for all (as it has 3rd party pthread libs) and a file name was not cased properly and linux did not like that

New Darknet archive to fix a case issue in a file name

---

CMake/External_Darknet.cmake
CMake/External_OpenCV.cmake
CMakeLists.txt

fletch_BUILD_WITH_CUDA was changed to fletch_ENABLE_CUDA, but it wasn't changed for all projects (e.g. CAFFE) so there's a bug in master since some things were using 1 flag but not the other.
I prefer BUILD_WITH_CUDA as opposed to ENABLE_CUDA because unlike all of the other packages, CUDA is not being built by fletch, just linked against, and the ENABLE_* would make it seems like it was building it like everything else.

Revert CUDA enable flag name

---

CMake/fletch-tarballs.cmake

This patch fixes an issue on Windows, 'Could not extract tarball filename from url:'

Use the file api from girder and include file name.

---

Doc/release-notes/release.txt
Patches/OpenCV3/Patch.cmake
Patches/OpenCV3/cv2.cpp

This fix works and is probably good enough for us.  A slightly better approach would be to use CMake to detect if the Python Debug libraries are found and only employ this hack if they are not.  I may try that approach in the future and push it upstream to OpenCV.

Fix OpenCV Python with Win32 Debug builds

---

Doc/release-notes/master.txt

It seems we didn't update the release notes when we added PyBind11 or GTest, so this PR makes that update.

Added release notes that were missed on previous branches

---

CMake/External_GFlags.cmake
CMake/External_GLog.cmake
CMake/External_GTest.cmake
CMake/External_LevelDB.cmake
CMake/External_OpenBLAS.cmake
CMake/External_PyBind11.cmake
CMake/External_VXL.cmake
CMake/External_libkml.cmake
CMake/fletch-tarballs.cmake

For many packages, the default download package is just a version number which makes it difficult to know which downloaded file goes with which package.

Provide an explicit download name for all packages without one.

---

CMake/fletch-tarballs.cmake
Doc/release-notes/master.txt

The current Protobuf in fletch is version 2.5.0. Howver, when Python 3 is enabled with Caffe, protobuf version 3 is required.
However using protobuf2 does not result in a build error. Instead an error is thrown when importing `pycaffe` a `TypeError` occurs (having to do with `str` and `unicode`). This is documented in https://github.com/BVLC/caffe/issues/5170. 
Note depending on whether this or #176 is merged first, the other should add the following code to `CMake/External_Caffe.cmake` to throw a configure-time error if python3 and protobuf 2.5 are enabled at the same time. 
```cmake
if(fletch_BUILD_WITH_PYTHON AND fletch_ENABLE_Protobuf)
if (${Protobuf_version} LESS 3.0 AND fletch_PYTHON_MAJOR_VERSION MATCHES "^3.*")
message(ERROR "Must use Protobuf >= 3.x with Python 3.x")
endif() …
```

Added option to use protobuf 3.4.1

---

CMake/External_GLog.cmake
CMake/fletch-tarballs.cmake
Doc/release-notes/master.txt

GLog contains a CMakeLists.txt. This branch removes the barrier to building on WIN32 to see if it just works.

Build glog windows

---

CMake/fletch-tarballs.cmake

@dstoup with respect to your comments from #222, after I updated to the most recent master I noticed that the Protobuf_SELECT_VERSION and FFmpeg_SELECT_VERSION options were visible even if their corresponding enable flag was false. This change fixes that so they only become visible once they are enabled. (The reason I didn't notice this with FFmpeg before was because its select version is an advanced option).

Hide Protobuf /FFmpeg select version when disabled

---

CMakeLists.txt

This ensures that the selected version information for enabled packages is propagated to the fletchConfig.cmake file. 
I'm not sure if its more desirable to do it implicitly like this, or explicitly in the External_*.cmake packages. However, the "_SELECT_VERSION" variable is often used to set the value of a normal "<pkg>_version" variable, which is used in those scripts. Perhaps the two should be consolidated? If not, then I think the implicit version is correct, because we are assuming that all user options regarding version will have the "_SELECT_VERSION" suffix.

logic to append all _SELECT_VERSION vars to the config

---

CMake/External_Caffe.cmake
CMake/External_Ceres.cmake
Patches/Caffe/527f97c0692f116ada7cb97eed8172ef7da05416/FindGlog.cmake
Patches/Caffe/527f97c0692f116ada7cb97eed8172ef7da05416/Patch.cmake
Patches/Caffe/527f97c0692f116ada7cb97eed8172ef7da05416/WindowsDownloadPrebuiltDependencies.cmake

Also a small fix to give Ceres a hint to find eigen
Note I converted tabs to spaces in the WindowsDownloadPrebuiltDependencies.cmake
The actual needed change was ~line 80
PATTERN "glog*" EXCLUDE
PATTERN "gflag*" EXCLUDE
I had to patch FindGlog because the find_package(glog) would find the glog-config.cmake but for whatever reason, it would NOT find the glog library. So I did this patch.
The find_package(gflags) in FindGflags.cmake uses gflags-config.cmake and finds the gflags lib, 
but glog.lib isnot found when find_package(glog) uses the glog-config.cmake

Fix for Ceres and Caffe to share the fletch glog and gflags

---

CMake/External_Caffe_Segnet.cmake
CMake/fletch-tarballs.cmake
Doc/release-notes/master.txt
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885 (copy)/CMakeLists.txt
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885 (copy)/Patch.cmake
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885 (copy)/cmake/ConfigGen.cmake
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885 (copy)/cmake/Dependencies.cmake
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885 (copy)/docs/CMakeLists.txt
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885 (copy)/examples/CMakeLists.txt
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885 (copy)/matlab/CMakeLists.txt
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885 (copy)/python/CMakeLists.txt
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885 (copy)/src/caffe/CMakeLists.txt
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885 (copy)/src/gtest/CMakeLists.txt
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885 (copy)/tools/CMakeLists.txt
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885/CMakeLists.txt
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885/Patch.cmake
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885/cmake/ConfigGen.cmake
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885/cmake/Dependencies.cmake
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885/cmake/Targets.cmake
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885/docs/CMakeLists.txt
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885/examples/CMakeLists.txt
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885/matlab/CMakeLists.txt
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885/python/CMakeLists.txt
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885/src/caffe/CMakeLists.txt
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885/src/gtest/CMakeLists.txt
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885/tools/CMakeLists.txt

I added a zip for this repository to girder : https://github.com/TimoSaemann/caffe-segnet-cudnn5
(Note that maybe out of date due to : https://github.com/TimoSaemann/ENet)
Anyway
What cool in this PR, is the patch, while all the caffe cmake files, allows you to uniquely identify your caffe fork when you do an external_project_add, provide a fork name (ex. -DCAFFE_FORK_SUFFIX:STRING=Segnet)
And the cmake patch files will post fix this to all the targets, configurations, install directories, etc. that it creates.
For this Segnet fork of caffe, it will create/install to the following:
fletch/install/headers/caffe_segnet
libraries and example binaries named : caffe_segnet
the cmake configuration name is updated to Caffe_SegnetConfig.cmake
Of course this will not work if the CMake files are …

Caffe segnet

---

README.rst

I needed to do this to get fletch build on a clean linux

Ceres requires Suitesparse with requires lapack (on ubuntu 16)

---

CMake/External_libgeotiff.cmake

Make the add_package_dependency of PROJ4 optional.
The system version seems to have issues on several linux distributions. Libraries are missing symbols which makes it  impossible for geotiff to link.
We are making the add_package_dependency optional to avoid the confusing error message about using the system version. We can safely make this call optional since we have the fatal error before it which forces enabling proj4.

Geotiff force fletch proj4

---

CMake/fletch-tarballs.cmake

This version will produce a proper DarknetConfig.cmake file that points to fletch install for includes/libs
Previously it pointed to the fletch darknet build directory, which does not exist in an install only fletch
After the builds, check the <fletch_DIR>/install/CMake/DarknetConfig.cmake and ensure you see 
set( Darknet_INCLUDE_DIR "<fletch_DIR>/install/include/darknet")
set( Darknet_LIBRARY_DIR "<fletch_DIR>/install/lib" )

New version of darknet

---

CMake/fletch-tarballs.cmake

This links to a new darknet zip that has a fix for the clock__gettime method not being on a mac but now is availavle on a mac with the new os high sierra, and a fix for CUDA 9

Darknet Update

---

Patches/OpenCV/2.4.13/OpenCVDetectCUDA.cmake

This patch was missed in the CUDA 9 updates.

Apply the Patch for compute_20 deprecation to OpenCV2

---

CMake/fletch-tarballs.cmake
Doc/release-notes/master.txt

Updates from 2.2.0 to 2.2.1 to get these changes: 
https://github.com/pybind/pybind11/blob/86e2ad4f77442c3350f9a2476650da6bee253c52/docs/changelog.rst#v221-september-14-2017
This is to address a build issue in my Caffe2 branch.
@KyleFromKitware I'm not sure if this breaks anything or introduces any issues for KWIVER / VIAME, From my understanding of the change log it seems like a safe upgrade to me. Do you have any intuition here?

Update pybind11 to 2.2.1

---

CMake/External_OpenCV.cmake
Patches/OpenCV/3.1.0/FindCUDA.cmake
Patches/OpenCV/3.3.1/FindCUDA.cmake
Patches/OpenCV/3.4.0/FindCUDA.cmake

OpenCV has issues when GPU support is enabled and the default complier is ccache. Nvcc is trying to use ccache directly and passing a -E argument which is invalid. This patch reallows the override of CUDA_HOST_COMPILER and alerts the user if they fall into the failure situation and provides advice on the fix.

Fix opencv nvcc ccache errors

---

CMakeLists.txt

Put the fletch config in both build and install locations for ease of use and consistency.

Fletch config belongs in build and install directory

---

Patches/PostgreSQL/Patch.cmake
Patches/PostgreSQL/src/bin/pg_rewind/copy_fetch.c

Change copy_file_range to rewind_copy_file_range because of new glibc function copy_file_range. This patch is valid through current versions of pg 10.

Patch potgresql glibc update

---

Doc/release-notes/master.txt
Patches/SuiteSparse/SuiteSparse_config.mk

CHOLMOD only uses metis if it is explicitly downloaded, which we don't do. Suitesparse usually builds without explicitly disabling metis, but fails on some machines. This branch explicitly disables the support until we decide it's important to include.

Explicitly disable metis support in CHOLMOD since we don't build it anyway

---

Patches/Qt/4.8.6/Patch.cmake
Patches/Qt/4.8.6/qfontengine_coretext.mm

Was experiencing error documented here: https://wiki.qt.io/Qt_5.9.5_Known_Issues#macOS, when attempting to compile Qt 4.8.6 on MacOSX High Sierra 10.13.4 (for castlegard)
Looks like Qt plans to patch this in a future update, as it is a known issue, so this is a temporary solution.

Fixing Qt 4.8.6 failing on High Sierra 

---

CMake/External_libkml.cmake

Change the exported KML variables from `LIBKML_*` to `KML_*`. This correctly matches the exported package name, and is necessary for consumers to be able to find KML automagically when using fletch.

Fix names of KML variables

---

CMake/External_qtExtensions.cmake

Fixed `qtExtensions_DIR` so it points to the correct directory that actually contains `qtExtensionsConfig.cmake`.

Fixed the setting of `qtExtensions_DIR`.

---

CMake/External_VXL.cmake
CMake/External_libgeotiff.cmake

This was done previously because a build of geotiff was not available in fletch. Now that it is, we need to pass geotiff to VXL otherwise vxl produces a library which causes conflicts.

Bug fix, vxl was forcing geotiff off if tiff was built

---

CMake/External_Qt.cmake

This branch contains two fixes to get Qt5 to build in Fletch on Windows with MSVC (tested on Visual Studio 2017).  The first is to disable the qtlocation module, which is broken.  This is a temporary fix and should be reverted once we have a solution to that build problem.  The second is to enable [dynamic loading](http://doc.qt.io/qt-5/windows-requirements.html#dynamically-loading-graphics-drivers) of OpenGL in Qt5.  Dynamic loading is not need to successfully build Qt5, but it is needed to build VTK against Qt5.  Also, this seems like the behavior we want anyway and is recommended by the Qt5 docs.

Fixes for Qt5 on MSVC

---

CMake/fletch-tarballs.cmake
Doc/release-notes/release.txt

Reverts Kitware/fletch#401.
VTK 8.1.1 is causing issues for some internal packages.

Revert "Dev/update to vtk 8.1"

---

CMake/fletch-tarballs.cmake

Update qtExtensions to bring in a bug fix for Windows consumers using Qt5.

Update qtExtensions again

---

CMake/External_GDAL.cmake

The _gdal_msvc_version required a big conditional block to cover
all versions and it was out of date, not supporting MSVC 15
(Visual Studio 2017).  However, there is no reason for the
conditionals since CMake provides the MSVC_VERSION variable with
exactly what is needed.

Remove _gdal_msvc_version in favor of CMake's MSVC_VERSION

---

CMake/fletch-tarballs.cmake

This is primarily due to an issue with GDAL where its if-defs are
improperly written such that if the host system has openjpeg version 2.2
or greater, GDAL sees those header files first and activates features
not available in 2.1.

Update openjpeg2 version to 2.3.0

---

CMake/External_Boost.cmake

This list of extra Boost libraries needs to be passed to the configure
script where BCP is run.  This commit also makes this list a cache variable
so it's easier for users to specify what extra Boost libraries they need.

Improve handling of Boost_EXTRA_LIBS

---

Patches/Boost/Configure.cmake

This solves the problem of downstream packages not being able to find Boost header files that they expect.
For header-only libraries, this is easier and more reliable than specifying additional libraries as `fletch_EXTRA_BOOST_LIBS`.

Copy all Boost header files to build/install tree

---

CMake/fletch-tarballs.cmake

Update to latest qtExtensions (again), bringing in a fix for persisting the user's "don't ask again" choice for `qtConfirmationDialog`.

Update qtExtensions (again)

---

CMake/fletch-tarballs.cmake

VNL is having C++ 11 related issues in ITK version 4. This new release seems to make that go away.

Update ITK to latest so it will build on Ubuntu 16.04

---

CMake/External_Qt.cmake

The qtlocation module is currently disabled for Qt5 for Windows. I am seeing build errors on both Linux and macOS as well so I would like to disable it for all platforms.

Disable Qt5 module qtlocation for all platforms

---

CMake/External_OpenCV.cmake
CMakeLists.txt

If one chose to install python' debug libraries (which are required to build debug fletch with opencv on windows) python discovery returns a list for python libraries. we need to parse that list and store libraries to the appropriate variables
Also, By default, OpenCV installed its python library to the site-packages where fletch found python, which may be Program Files where the build cannot write
We need to make a consistent location in the fletch build for libraries to put their build python packages. This PR has that for OpenCV. Note for some packages (like Caffe) there is no way to direct where their build puts their built python packages

Support python debug libs + python lib installs

---

CMake/External_VTK.cmake
CMake/fletch-tarballs.cmake

Add ability to select a pre-release of VTK 8.2. This is needed for [TeleSculptor](https://github.com/Kitware/maptk), which depends on post-8.1 changes, and because 8.2 is not officially released yet. (Later, this will be replaced with the official 8.2 release, at which point likely 8.1 will be dropped.)

Add VTK 8.2-pre

---

CMake/Utils.cmake

From the CMake documentation:
if(DEFINED <variable>)
True if the given variable is defined. It does not matter if the variable is true or false just if it has been set. (Note macro arguments are not variables.)
In the case of var_FOUND we want it to be true so would prefer the syntax ...
if(<variable>)

The add_package_dependency macro was incorrectly checking for FOUND variable DEFINED, which is not what we want

---

CMake/External_VXL.cmake
CMake/FindGEOTIFF.cmake
Doc/release-notes/master.txt

We should not be requiring geotiff in VXL. This branch removes the hard requirement but also fixes the problems VXL has finding geotiff when it exists on the system. Now if fletch builds geotiff or it's installed on the system, VXL will have access to it. If it doesn't exist though, VXL still tries to build its very old version.

Remove the hard geotiff requirement from VXL

---

CMake/External_VTK.cmake

Fletch does not run the package tests anyway, so this will save build time.

Disable building the VTK tests

---

Patches/OpenCV_contrib/3.4.0/Patch.cmake
Patches/OpenCV_contrib/3.4.0/modules/freetype/CMakeLists.txt

This was a problem with OpenCV 3.4.0 on MacOS using freetype from macports
See also upstream PR here
https://github.com/opencv/opencv_contrib/pull/1972

Patch OpenCV_contrib MacOS linker issue

---

CMake/External_libgeotiff.cmake
Doc/release-notes/master.txt

This PR makes libtiff and libjpeg-turbo requirements to build libgeotiff.
When you only enable libgeotiff (and its hard dependency proj4), libgeotiff fails to build and you get these errors:
This error is from libjpeg not being built
```
make[5]: *** No rule to make target `/Users/taylorcook/kitware/fletch/src/build/install/lib/libjpeg.dylib', needed by `lib/libgeotiff.2.1.2.dylib'.  Stop.
make[4]: *** [CMakeFiles/geotiff_library.dir/all] Error 2
```
This error is from libtiff not being built
```
Scanning dependencies of target geotiff_library
[  2%] Building C object CMakeFiles/geotiff_library.dir/cpl_serv.c.o
In file included from /home/kitware/jenkins/workspace/fletch/build1/build/src/libgeotiff/geo_tiffp.h:37:0,
from /home/kitware/jenkins/workspace/fletch/build1/build/src/libgeotiff/cp …
```

Fix libgeotiff depends

---

CMake/External_GDAL.cmake
Doc/release-notes/release.txt

This change seems to fix my issue on macOS.  It seem like it might be relevant on other platforms too.

Add GDAL dependency on libxml2

---

CMakeLists.txt
Doc/release-notes/release.txt

The concrete reason for this change is a bug I found with CUDA on Windows.  By default, CUDA is installed in ` C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2` but importing `fletchConfig.cmake` into KWIVER set `CUDA_TOOLKIT_ROOT_DIR=C:/Program;Files/NVIDIA;GPU;Computing;Toolkit/CUDA/v9.2` which caused all sort of problems.
The solution is to add quotes around the path in `fletchConfig.cmake`.  I've done this for `CUDA_TOOLKIT_ROOT_DIR` and `fletch_ROOT`, which are user configurable an may contain spaces.  There are many other paths in the file that could be quoted for added safety, but I don't think they will be a problem since the paths are hard coded relative to `fletch_ROOT`.  However, if someone else wants to add the missing quotes it's probably not a bad idea.

Quote exported paths

---

CMake/External_YAMLcpp.cmake

This type causes YAML to be downloaded even if it has already been done.

Fix typo in CMake symbol name.

---

CMake/External_GDAL.cmake
Doc/release-notes/release.txt

GDAL was installing it's data files into ${fletch_INSTALL}/data on Windows but ${fletch_INSTALL}/share/gdal on other platforms.  This patch sets the DATADIR variable to make GDAL put it's files in a consistent location on Windows too.

Set GDAL datadir on win32

---

CMake/External_PNG.cmake
CMake/External_ZLib.cmake
CMake/fletch-tarballs.cmake
Patches/ZLib/CMakeLists.txt
Patches/ZLib/Patch.cmake

Prerequisite to #502 
Update ZLib from version 1.2.8 (or 1.2.3 according to the CMakeLists.txt) to version 1.2.9, which is required to build libkml 1.3.0 for this PR #502.
This also changes the ZLib source from a Kitware fork to an official ZLib release. (Injecting our custom CMakeLists.txt to build it)
...as well as a bonus ZLib library find fix for Apple

update ZLib to 1.2.9, fix ZLib find errors

---

CMake/External_GDAL.cmake
Doc/release-notes/master.txt

Prevent GDAL from failing as a result of picking up an old libkml version.

disables GDAL with libkml

---

CMake/External_VTK.cmake
CMake/fletch-tarballs.cmake

Select VTK rendering backend based on VTK version, rather than Qt version. Update from 8.0.0 to 8.0.1. These changes¹ are needed by ViViA, which is [working on transitioning to Qt5](https://github.com/Kitware/vivia/pull/47), but still requires VTK 8.0 due to [API breakage](https://gitlab.kitware.com/vtk/vtk/merge_requests/3451#note_462858) and has not yet been ported to VTK's OpenGL2 backend (which is also suspected of being flaky in 8.0).
Our other main consumer, TeleSculptor, which does use the OpenGL2 backend, requires VTK 8.2.
(¹ Well, pedantically, just the backend selection stuff; I want to update to 8.0.1 because it's what I'm using locally, but I don't know that it's required for anything.)

VTK fixes for ViViA

---

Patches/OpenCV/3.4.0/Patch.cmake
Patches/OpenCV/3.4.0/cvdef.h
Patches/OpenCV/3.4.0/test_mat.cpp

OpenCV fails on Windows when "QT_version = 5.11.2":
` dual_filter_view.hpp(85): error C2079: 'cvv::view::DualFilterView::rawImages_' uses undefined class 'std::array<cv::Mat,2>' ` (https://open.cdash.org/viewBuildError.php?buildid=5752586)
OpenCV 3.4.0 -> 3.4.1 contains the patch that fixes the bug:
(https://github.com/Microsoft/vcpkg/issues/3024)
However... Darknet doesn't seem to play nice with OpenCV 3.4.1, yet. (https://github.com/pjreddie/darknet/issues/502)
Soo.... patch OpenCV 3.4.0 with the patch we need.
This should be the last step required to get Qt5 as the default Qt version.

opencv dual_filter_view patch for windows

---

CMake/External_ITK.cmake

ITK is trying to build before OpenCV has finished building, and errors because ITK can't find OpenCV.
This PR fixes it.
```
CMake Error at Modules/Video/BridgeOpenCV/itk-module-init.cmake:4 (find_package):
By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "OpenCV", but
CMake did not find one.
Could not find a package configuration file provided by "OpenCV" with any
of the following names:
OpenCVConfig.cmake
opencv-config.cmake
Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
"OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
provides a separate development package or SDK, be sure it has been
installed.
Call Stack (most recent call first): …
```

Fix OpenCV ITK depends

---

CMake/fletch-tarballs.cmake
Doc/release-notes/master.txt

Recently approved change in KWIVER (Kitware/kwiver#799) require newer FFMPEG for fast accurate seeking in the FFMPEG arrow.  Some tests will fail if we use the older version 2.6.2.
The only potential downside is that the old VXL implementation (vidl_ffmpeg) used in KWIVER may not work as reliably with the new FFMPEG.  I suggest we update the default version but continue to support 2.6.2 as an option.  This will force us to either update or abandon vidl_ffmpeg.

Update FFMPEG default version to 3.3.3

---

CMake/External_PDAL.cmake

This helps packages using Fletch to provide PDAL find version that is in Fletch.

Set PDAL_DIR

---

CMake/External_GDAL.cmake

If we don't explicitly disable openjpeg, GDAL will find it and include the plugin. If GDAL has both mrsid and openjpeg plugins, it favours openjpeg which is not capable of opening some of our nitf files..

When enabling mrsid in gdal, explicitly disable openjpeg

---

CMake/fletch-tarballs.cmake

This changes the yasm target source from tortall.net to github, I think this will allow for better uptime on the link.

update yasm source link to github, current one is dead and unstable

---

dockerfile

Adds the following parameters:
- BASE_IMAGE
- PY_MAJOR_VERSION
- ENABLE_CUDA
These can be specified at 'docker build' time:
`docker build -t fletch:latest --build-arg BASE_IMAGE=ubuntu:16.04 . `

parameterize the dockerfile to accept build args

---

CMakeLists.txt

Newer CMake versions require generator platform and toolkit passed to ExternalProject_Add

Pass EP generator platform and toolkit

---

Patches/Qt/5.11.2/Patch.cmake
Patches/Qt/5.11.2/qtserialbus/src/plugins/canbus/socketcan/socketcanbackend.cpp

Qt can't resolve symbol SIOCGSTAMP with updated kernel headers. Including linux/sockios.h is a dirty, short-term, quick-fix patch until Qt fixes the issue from within their OS layer.

Patch qt socket include

---

CMake/External_ITK.cmake
CMake/External_VTK.cmake

The default VIAME build currently fails when Python wrappings for VTK are enabled in Python 3.7. While it might be possible to fix this in VIAME by updating the default VTK version, an alternative option is to simply disable `VTK_WRAP_PYTHON`. This has the additional benefit of shortening build time. 
I added a new option `fletch_ENABLE_VTK_PYTHON`, which does this. It defaults to "ON", so original behavior is preserved. I modified the warning messages so no warning will happen when fletch_ENABLE_VTK_PYTHON is OFF. 
Lastly, this local block of code has a inconsistency in spacing after "if" statements, so I modified those to make them consistent while I was editing the file.

Add option to enable/disable VTK Python wrappings

---

CMake/fletch-tarballs.cmake

Please see:
http://eigen.tuxfamily.org/index.php?title=News:Migration_to_GitLab.com_scheduled_on_the_December_4th

update eigen source to gitlab, bitbucket is a deprecated host

---

CMake/External_Caffe.cmake

Our Caffe version can't support python 3 with a Visual Studio version >= 2017

We can't build this caffe version with py3 and VS >= 2017

---

CMake/fletch-tarballs.cmake

Make Caffe version selectable. The options are for either version 1 or version 2, with 2 being the default.

Make caffe version selectable

---

CMake/fletch-tarballs.cmake

Update the location of the Qt source packages. The old location still exists, but several packages, including the Qt5 version we are using, have gone missing.

Fix Qt location

---

CMake/External_OpenCV.cmake

The current config option forces OpenCV to depend on Qt when built. The option is also advanced which makes it difficult for users to know or remember that they might want to turn it off. That dependency isn't needed for most user but significantly increases the build time since OpenCV needs to wait for Qt to finish before it can begin.

Break the forced dependency of Qt on OpenCV.

---

CMake/External_Darknet.cmake
Patches/Darknet/CMakeLists.txt
Patches/Darknet/Patch.cmake

The Examples fail to link on Windows. Patching the CMakeLists to add an option to disable them.

Patch darknet no examples

---

CMake/fletch-tarballs.cmake

Aside from bringing PostGIS to a more modern version that's still compatible with the other current database packages, this upgrade version introduced a bug fix to allow consistent parallel builds of raster. Previous versions attempted a dependant library, rtloader at the same time as building its required corelib. This would lead to build failures on some systems.

Update PostGIS version

---

Patches/Boost/1.65.1/Patch.cmake
Patches/Boost/1.65.1/visualc.hpp

This PR removes the 'Unknown compiler...' warning that floods the logs in Visual Studio builds.

Remove boost compiler warning

---

Doc/release-notes/release.txt
Patches/Darknet/3rdparty/dll/CMakeLists.txt
Patches/Darknet/3rdparty/lib/CMakeLists.txt
Patches/Darknet/CMakeLists.txt
Patches/Darknet/Patch.cmake

This patch is the last known issue with building Fletch/kwiver on Visual Studio 2019. Darknet was using `if( NOT "${CMAKE_GENERATOR}" MATCHES "(Win64|IA64)" )` to determine if it should install the  x86 or x64 pthread lib and dll. That approach isn't consistent with newer CMake which removed the CMAKE_GENERATOR_PLATFORM from CMAKE_GENERATOR. It's more appropriate now to compare CMAKE_GENERATOR_PLATFORM directly which produces "(x64|ARM64)" for the 64-bit versions.
This PR depends on #608 which is in review now too. I will land that one first.

Patch darknet pthread install

---

CMake/fletch-tarballs.cmake

There were several sourceforge urls that looked like it might be an older style .. http://downloads.sourceforge.net/. Those were fixed to what looks like a currently accepted pattern.

Fix broken sourceforge urls

---

Patches/VXL/Patch.cmake
Patches/VXL/core/vbl/vbl_array_2d.h

The main reason for this patch is because Fortify calls out this defect. It is a potential issue so the fix is good. We need to patch since we aren't able to move to VXL master yet. But, I will push this fix upstream so it's there when we are able.

Patch vxl buffer overflow

---

CMake/External_Protobuf.cmake

This PR updates the protobuf build to support static build that is used for kwiver wheel.

Add configuration parameters for static protobuf build

---

CMake/External_Eigen.cmake

Instead of setting variables needed to make `FindEigen3.cmake` work, export `Eigen3_DIR` instead so that consumers that need Eigen will find its `Eigen3Config.cmake`.

Point users to Eigen3Config.cmake instead

---

Doc/release-notes/master.txt
Patches/Boost/Common.cmake

Without the --ignore-site-config, Boost tries to use a system installed Boost's config. That can cause a build error by altering the Fletch Boost parameters.

Don't use a system Boost site-config.

---

CMake/External_GDAL.cmake
CMake/fletch-tarballs.cmake

I'm making this PR because I kept getting errors when trying to build fletch while my conda environment was enabled. Ideally this shouldn't influence anything because fletch builds all of its dependencies from source. However, due to GDAL's configuration system, I was finding that it the build process kept pulling incorrect libraries for proj4. This was weird because there is literally a `--with-proj=${PROJ4_ROOT}` flag passed to the gdal configure command in the External_GDAL.cmake file. Yet, it kept trying to include a "proj.h" file from my conda directory. 
I found out the reason was because GDAL found curl in my conda directory, which added my conda include and lib to the include / library search paths, which also included proj. Therefore there was no way for GDAL to determine which …

Build GDAL without curl, netcdf, kea, and use fletch geos

---

CMakeLists.txt
Doc/release-notes/master.txt

CMP0074 allows CMake to search prefixes specified by <PackageName>_ROOT.

Set cmake policy CMP0074

---

CMake/External_GDAL.cmake

GDAL v1 gets confused by other json.h files on the system. It's a popular header name from other json related packages. This PR sets json-c to internal so GDAL builds its own version.

Disable json-c from GDAL v1

---

Doc/release-notes/release.txt
README.rst

This PR adds a new Troubleshooting section to the README and adds an entry to document the solution to a common build error in Boost that happens after upgrading your MSVC version.

Add readme troubleshooting msvc upgrade boost

---

CMake/External_VTK.cmake
Doc/release-notes/release.txt

I was still getting the warning message about using VS 2015 and VTK < 7 even when using more recent VTK and more recent VS.

Fix VTK Python bindings with MSVC

---

CMake/External_VTK.cmake

The CMake options for enabling modules have changed in VTK 9, so setting the old options was no longer enabling Qt support in VTK 9.  Note that QtWebKit is not longer a sub-option, so we can just turn the whole Qt group on.

VTK 9 uses different CMake options for modules than VTK 8

---

CMake/External_Caffe.cmake
CMake/External_Caffe_Segnet.cmake
CMake/External_Darknet.cmake
CMake/External_OpenCV.cmake
CMake/fletch-tarballs.cmake
Doc/release-notes/master.txt

Add the latest (as of today) OpenCV version, 4.5.1 since 4.2 is still not recent enough to support CUDA 11.  If 4.5.1 works for everyone we can likely remove 4.2 support.
The last commit makes 4.5.1 the default for dashboard testing purposes.

Upgrade OpenCV to 4.5.1

---

Patches/GDAL/2.3.2/Patch.cmake
Patches/GDAL/2.3.2/ogr/ogrsf_frmts/geojson/libjson/GNUmakefile

This patch updates the _XOPEN_SOURCE macro to 600 so GDAL's libjson
finds strdup(). Via https://bugs.launchpad.net/libvterm/+bug/1638205

Patch GDAL to build on OSX (fixes missing strdup() prototype).

---

Patches/VTK/8.2/Patch.cmake
Patches/VTK/8.2/ThirdParty/exodusII/update.sh
Patches/VTK/8.2/ThirdParty/exodusII/vtkexodusII/src/ex_create_par.c
Patches/VTK/8.2/ThirdParty/exodusII/vtkexodusII/src/ex_open_par.c

Patch VTK 8.2 to fix a build issue when using gcc v10. vtkExodusII complains about "multiple definition of `exodus_unused_symbol_dummy_1'"
The VTK issue is written up here and is merged into master as of a year ago:
https://gitlab.kitware.com/vtk/vtk/-/issues/17774
This patch was taken from Slicer. Details posted here:
https://discourse.slicer.org/t/build-fails-in-vtkexodus-on-linux/12018/5

Patch vtk8.2 gcc10

---

CMake/External_GDAL.cmake
CMake/External_PDAL.cmake
CMake/External_PROJ.cmake
CMake/External_PostGIS.cmake
CMake/External_VTK.cmake
CMake/External_libgeotiff.cmake
CMake/fletch-tarballs.cmake

Update PROJ to 5.2. Rename from PROJ4 to PROJ.
Note that, due to a major API change between PROJ 4 and later versions of PROJ, our find module, which looks for the PROJ 4 API, intentionally remains "PROJ4".

Update to PROJ 5.2

---

Doc/release-notes/master.txt
Patches/VTK/8.0/CMake/VTKGenerateExportHeader.cmake
Patches/VTK/8.0/Patch.cmake
Patches/VTK/8.2/CMake/VTKGenerateExportHeader.cmake
Patches/VTK/8.2/Patch.cmake

VTK's gcc version check is failing to detect version 10.2. That causes everything to get built with hidden visibilty which causes link errors. Considering it's trying to prevent a gcc < 4.2, it's safe to just remove the code for our purposes. We don't support such old compilers.

Patch vtk8.x gcc version check error

---

Patches/VXL/Patch.cmake
Patches/VXL/v3p/openjpeg2/opj_includes.h

With the latest updates to Visual Studio 2019, this openjpep2 header in VXL starting causing compilation problems.  Apparently the `lrintf()` function has been provided by Visual Studio since 2013 and the `else` case on `#if !defined(_WIN64)` served to define that function for even older VS compilers.  However, something has changed in the lastest VS 2019 where that code is now conflicting with the VS provided definition.  So the easy fix is to just remove that definition.  This should work for all compilers supported by Fletch.
I'm not sure if this is the right fix for upstream VXL because I don't know the oldest version of VS supported by VXL.  Though I doubt the support VS older than 2013 at this point.
I'm actually not even sure why I'm hitting this problem since I'm building …

Patch VXL for VS 2019 compile issue

---

CMake/External_PNG.cmake

The static build for zlib is called libz.a rather libzlib.a. Thus PR checks if the build is static or dynamic and provides the zlib name based on the type of build

Conditionally update zlib name in get_system_library_name

---

CMake/External_FFmpeg.cmake

Disable FFMPEG assembler optimizations on static build to allow libavcodec to build with fpic enabled. Necessary for Kwiver wheel building.

Disable FFmpeg assembler optimizations

---

Patches/Caffe/7f5cea3b2986a7d2c913b716eb524c27b6b2ba7b/Patch.cmake
Patches/Caffe/7f5cea3b2986a7d2c913b716eb524c27b6b2ba7b/cmake/Modules/FindvecLib.cmake
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885/Patch.cmake
Patches/Caffe_Segnet/abcf30dca449245e101bf4ced519f716177f0885/cmake/Modules/FindvecLib.cmake

This PR provide a more general path the Apple Frameworks so it can find vecLib. The previous FindvecLib passed in a very specific MacOS version, 10.9.sdk. I've added the path with MacOSX.sdk which points to the correct system.

Patch caffes framework path

---

Patches/Boost/1.65.1/Patch.cmake
Patches/Boost/1.65.1/debugger.c
Patches/Boost/1.65.1/execcmd.c
Patches/Boost/1.65.1/filesys.h
Patches/Boost/1.65.1/fileunix.c
Patches/Boost/1.65.1/jam.c
Patches/Boost/1.65.1/make.c
Patches/Boost/1.65.1/path.c
Patches/Boost/Common.cmake

Boost's b2 utilities is missing a ton of headers which are causing implicit-function errors. It's started showing up in darwin, Apple clang version 12.0.0.
The patch is useful for all distributions though since the problem is likely to show up in more places as compliers get more strict.

Patch boost implicit function errors

---

CMake/External_VXL.cmake

It turns out that my previous patches to fix the VXL build were never actually being applied.  I had locally applied them so I didn't notice until a did a clean build.
This also means that the previous existing patch for VXL was never applied either.  Maybe it's not longer needed?  Maybe we should just update VXL from upstream?  I think my patch was fixed upstream, but in a different way.

Actually apply VXL patches

---

CMake/External_libjpeg-turbo.cmake
Patches/libjpeg-turbo/simd/CMakeLists.txt

The clear intent of the original CMakeLists.txt that we patched was to run nasm(yasm) with -g in Debug or RelWithDebInfo. We removed those lines and added -g v8 to the CMake arguments. The new CMake 3.20.1 is not happy with those args added in the way we were doing it so libjpeg-turbo stopped configuring. This patch moves those arguments into its expected location and  condition.

Move the nasm args into the already patched CMakeList.txt for simd

---

README.rst

Update outdated mentions of `fletch_ENABLE_PYTHON` to `fletch_BUILD_WITH_PYTHON`.

Update docs CMake Python flag

---

CMake/External_VTK.cmake

Keeping this option enabled can cause build issues on some platforms and adds a lot of time to the build, especially in Visual Studio. I don't see why it should be marked as advanced. It is better to have the option exposed so folks can remember that it's there before taking so much time building it. VTK is about the last build to finish because of Qt so seeing the failure at the end can be painful.

Remove the advanced marking for the fletch_ENABLE_VTK_PYTHON option.

---

CMake/External_libkml.cmake

Not all *nix systems have expat headers installed. Check if CMake finds expat and use if it does, otherwise let libkml build internally.
Fixes issue #214

Fix libkmls expat support based on CMake find_package

---

Doc/release-notes/v1.5.0.txt
Patches/GTest/Patch.cmake
Patches/GTest/googletest/src/gtest-death-test.cc

GTest fails with gcc11 builds in Debug mode. We are now seeing -Werror=maybe-uninitialized. This patch just initializes the variable in question.

Patch gtest gcc11

---

CMake/External_VTK.cmake

Only enable Qt in VTK if Qt is present. The diff is less than it looks since I just wrapped the Qt setup in an `if(QT_FOUND) - endif()`.

Only enable Qt in VTK if it is present

---

Doc/release-notes/master.txt
Patches/FFmpeg/4.4.1/Patch.cmake
Patches/FFmpeg/4.4.1/mpegtsenc.c

Add a patch modifying FFmpeg to write metadata descriptor structures when writing synchronous KLV to a MPEG-TS file. This is to be in compliance with MISB ST1402.

Add patch to write KLV descriptors

---

Patches/Boost/1.65.1/Patch.cmake
Patches/Boost/1.65.1/exec.cpp

Boost 1.65.1 uses the private python API function, _Py_fopen which is removed in python 3.10. Switch to using the public fopen function instead.

Patch boost python 3.10

---

Patches/PDAL/1.7.2/Patch.cmake
Patches/PDAL/1.7.2/PlyReader.hpp

Change `std::istream::streampos` to `std::streampos`, since the former doesn't exist in some modern compilers.

Patch PDAL PlyReader

---

CMake/External_FFmpeg.cmake
CMake/External_msys2.cmake
CMake/External_x265.cmake
CMake/fletch-tarballs.cmake

This PR adds support for the x265 library. x265 provides a FFmpeg-compatible H.265/HEVC video output codec.

Add x265 support

---

CMake/External_msys2.cmake

This PR ensures that multiple sub-projects which use MSYS2 to build on Windows don't run into redefinition errors when including the MSYS2 file from both sub-project files.

Add msys include guard

---

CMake/External_Boost.cmake
CMake/fletch-tarballs.cmake
Patches/Boost/Install.cmake
Patches/Qt/5.11.2/Patch.cmake

This has become a sort of combination PR of changes which fix issues that came up when upgrading our CI systems/compilers (#707, #708, #710). The idea with combining them here is to demonstrate that CI can "pass" with all of them together, since if we ran CI on each of them individually we would run into the problems the still exist in `master` but are fixed in the other PRs, preventing the CI from running all the way. It's not intended to be merged like this - we can merge the other PRs one at a time, then this one rebased on `master` - just don't expect their CI to fully pass.
Note that Linux GPU, Mac, and Windows are still failing. However, I wouldn't count these as true "failures" in their current state:
- Linux GPU just always fails due to config issues
- Windows successfully builds …

Upgrade Boost to 1.78.0

---

CMake/External_ffnvcodec.cmake

Not sure how this syntax error snuck through.  I guess our dashboard build for Windows doesn't have CUDA.

added missing closing brace

---

CMake/External_ffnvcodec.cmake

This PR addresses further typos in the Win32 ffnvcodec CMake script, which apparently never got tested and is nonfunctional.

Fix Windows ffnvcodec script

---

Doc/release-notes/master.txt
Patches/FFmpeg/4.4.1/Patch.cmake
Patches/FFmpeg/4.4.1/libx264.c
Patches/FFmpeg/4.4.1/libx265.c
Patches/FFmpeg/4.4.1/nvenc.c
Patches/FFmpeg/4.4.1/nvenc.h

MISB ST0604 states that MISP frame timestamps should be put in the "SEI unregistered user data" field of H.264 and H.265 video streams. Our most recent version of FFmpeg, 4.4.1, implements _reading_ of these fields but not writing. This PR pulls in more recent feature additions from the public FFmpeg repository, adding only the code necessary to write these fields (or, more accurately, to tell x264, x265, and nvenc to write these fields).

Patch FFmpeg to write unregistered SEI user data

---

CMake/External_x265.cmake
Patches/x265/Patch.cmake
Patches/x265/sei.h

When writing MISP frame timestamps to H.265 video, ST0604 states that you are supposed to write in the "SEI unregistered user data" field with a specific UUID as the "key" that indicates what kind of data the timestamp is. x265 does allow writing to this field, but will only write its own custom x265 UUID as the "key". This patch just cuts that out, so the user-provided UUID is written in its place.

Patch out x265 SEI UUID

---

CMake/fletch-tarballs.cmake
Patches/FFmpeg/5.1.2/Patch.cmake
Patches/FFmpeg/5.1.2/mpegts.c

This PR adds v5.1.2 as a version option for FFmpeg, and ports over the one patch from v4.4.1 that is still relevant to v5.1.2.

Add FFmpeg v5.1.2

---

CMake/External_Qt.cmake

When configuring Qt on Linux using Makefiles, `make` may encounter a [fatal error](http://canifis:8080/view/Fletch/job/FletchLinuxNightly/31/consoleFull) or warning, depending on the version of `make`. This is due to `./configure` internally calling `make`, but because that call is hidden inside `./configure`, the parent `make` does not know about it. However, thanks to the `MAKEFLAGS` environment variable, the child does know about the parent, and attempts to coordinate jobs with it. This fails, as the parent is not expecting a child `make` instance; hence the error/warning.
This PR fixes the issue by including in the configure command the string `$(MAKE)`, which, even though it doesn't actually do anything here, signals to the parent `make` instance to expect a child `make`, allowing …

Fix Qt configure make jobserver bug

---

CMake/External_Qt.cmake

Turns out that the Ninja generator does not like #729 (see [here](http://canifis:8080/view/Fletch/job/FletchLinuxNightly/38/console)), so this PR adds a check that we are using Makefiles before applying that fix.

Target the Qt fix to only Makefiles

---

CMake/External_pybind11.cmake

This PR fixes a mysterious bug in some GCC builds of KWIVER. When pybind11 is enabled, it can sometimes override the C++ standard level in KWIVER for those files that are building against pybind11 using [`INTERFACE_COMPILE_OPTIONS`](https://cmake.org/cmake/help/latest/prop_tgt/INTERFACE_COMPILE_OPTIONS.html) in CMake. Our pinned version of pybind11 in fletch is old enough so that the newest version it will set itself to is C++14. So any C++17 features in headers included by KWIVER's python module will throw an error when pybind11 overrides the version back down to 14. Luckily, this can be fixed by just telling pybind11 to use C++17.

Set pybind11 to build with C++17

---

CMake/fletch-tarballs.cmake

This fixes an issue where FFmpeg did not appear as an option when configuring with ccmake. The addition of ffmpeg to fletch_external_sources was enclosed by if/endif block keeping it from being added unless FFmpeg was enabled on the command line by cmake.

FFmpeg now shows up as an option in ccmake

---

CMake/External_libkml.cmake
CMakeLists.txt

Our versioning is somewhat messed up here. There is a `v1.5.0` tag, but its `CMakeLists.txt` version is `1.4.1`. Also, it has commits in it that the `release` branch does not have? Neither of these make sense, so this PR attempts to fix them by updating the version number and merging `v1.5.0` into `release`. We should probably make a `v1.5.1` release soon to get this all in a clean state.

Fix versioning

---

CMakeLists.txt
Doc/release-notes/master.txt
Doc/release-notes/v1.6.0.txt

This PR enacts the release to v1.6.0. I'll update the `release` branch and create a new tag accordingly when this merges.

Release v1.6.0

---

.dockerignore
dockerfile

This PR cleans up the `Dockerfile`, which has not been building properly for a long while. Notable changes include removal of the `PY_MAJOR_VERSION` argument (`python2` is long deprecated) and the neat `COPY --from=base / /` trick which reduces the size of the resulting container dramatically (`20GB -> 3GB`) by removing the layers describing the changes to intermediate build files, keeping only the installed final product.

Clean up Dockerfile

---

Patches/FFmpeg/4.4.1/mpegts.c
Patches/FFmpeg/5.1.2/mpegts.c

This PR moves the logic which records whether a KLV stream is synchronous or asynchronous to outside of some `if` statements it doesn't need to be in.

Adjust KLV sync/async detection

---

CMake/External_GDAL.cmake

Without this, loading GDAL was failing to find its dependencies (e.g., `libproj.so.18`) when not in a standard location.

gdal: ensure that an rpath to the install tree is set

---

Patches/FFmpeg/5.1.2/Patch.cmake
Patches/FFmpeg/5.1.2/mpegtsenc.c

Apparently I missed this patch when porting from 4.4.1 to 5.1.2.

Add FFmpeg patch to write synchronous KLV descriptor

---

Patches/FFmpeg/4.4.1/mpegtsenc.c
Patches/FFmpeg/5.1.2/mpegtsenc.c

The standard only requires us to write the registration descriptor when the KLV stream is asynchronous; currently we always write it.

Only write registration descriptor when async

---

Patches/FFmpeg/4.4.1/mpegtsenc.c
Patches/FFmpeg/5.1.2/mpegtsenc.c

The [SDT](https://en.wikipedia.org/wiki/Service_Description_Table) is automatically inserted by FFmpeg whenever it writes a transport stream. This PR adds an option to disable that insertion, to opt out of the default service metadata (`service_name: Service01`, `service_provider: FFmpeg`) being added in. The SDT was designed for e.g. broadcast television and is likely useless in computer vision applications.

Add option to omit writing SDT

---

README.rst

Updated the FLETCH build guide with the following:
- Updated version descriptions for dependencies
- Removed deprecated build from docker image instructions
- Minor grammatical editing

Update FLETCH build guide

---

CMake/fletch-tarballs.cmake

Goal : 
- Fix bugs to build on windows
Changes : 
- Fix:
- Update link of msys2 because current link does not exist any more
- Refact:
- Update links of ffmpeg to point on data.kitware instead of release page of ffmpeg.
The changed above are tested to build successfully on windows 10 and ubuntu 22.

Fix msys2 link

---

CMake/fletch-tarballs.cmake

Update some of the defaults for packages so the defaults match what is currently used by the upcoming kwiver version 2 release.

Update package defaults to reflect needs for kwiver-v2
