Kitware/fletch

- Patches/libtiff/Install.cmake
> Add missing CMake Install patch

- Patches/Qt/Patch.cmake
- Patches/Qt/gui/painting/qpaintengine_mac.cpp
API: CMGetProfileByAVID & CGColorSpaceCreateWithPlatformColorSpace
have been deprecated for quite some time and are a removed from
El Capitan.
> Add Qt Patch for Mac to avoid deprecated API

- Patches/OpenCV/OpenCVDetectCUDA.cmake
- Patches/OpenCV/Patch.cmake
> Fix CUDA arch detection for CUDA > 6.5

- CMake/fletch-tarballs.cmake
The previous version is no longer available from their website.
> Update HDF5 url and version.

- CMake/External_Ceres.cmake
- CMake/External_PROJ4.cmake
- CMake/External_SuiteSparse.cmake
- CMake/External_VTK.cmake
Export various additional variables to fletchConfig.cmake to help find Fletch packages
> improve config exports

- CMake/External_OpenCV.cmake
- CMake/fletch-tarballs.cmake
Missing packages include PNG, libtiff, jpeg and Eigen.
> Pass packages to OpenCV.

- CMake/External_GFlags.cmake
This corrects what looks to be a copy-paste error.
> Added GFlags_ROOT variable, removed duplicate GLog_ROOT

- CMake/External_GFlags.cmake
- Patches/GFlags/Patch.cmake
- Patches/GFlags/windows_port.cc
- Patches/GFlags/windows_port.h
https://github.com/gflags/gflags/commit/366e9d335c4b5b12135e73808d6b47ab19dd7379
> Fix GFlags compilation on VC2015 with a patch from upstream

- CMake/External_OpenCV.cmake
- CMake/External_OpenCV_contrib.cmake
- CMake/External_Qt.cmake
- CMake/fletch-tarballs.cmake
- CMakeLists.txt
- Patches/Qt/configure
- Patches/libjson/cmakeify/JSONOptions.h.in
- README.md
Optionally add support for OpenCV 3. This branch takes the previously developed commits and moves them into the existing master. It became too stale to rebase.
> Add opencv3 support

- CMake/External_Boost.cmake
@aaron-bray can you have a look?
> Escape the backslashes in the Boost section of fletchConfig.

- Patches/OpenCV_contrib/Patch.cmake
- Patches/OpenCV_contrib/hdf/hdf5.cpp
- Patches/OpenCV_contrib/hdf/hdf5.hpp
This branch addresses build errors on recent versions of Ubuntu by applying an upstream patch from OpenCV.
> Fix OpenCV HDF5 build error

- Patches/OpenCV_contrib/hdf/hdf5.cpp
Back ported upstream OpenCV changes to fix build errors
in Visual Studio relating to the use of HDF5.
See upstream changes here:
https://github.com/opencv/opencv_contrib/pull/547
> Fixed HDF5 build errors in OpenCV on Windows.

- README.md
- README.rst
Fletch is in serious need of a README that is more than one sentence.  Here is a start.
> Give Fletch a real README

- Doc/release-notes/1.1.0.txt
This is mostly to put the file in place.  @mattdawkins and @hughed2 should probably update my description of what already has landed in master since v1.0.0.
> Create v1.1.0 release notes

- Doc/release-notes/1.1.0.txt
@mleotta Have a look to make sure the additions I've made follow the format you're expecting.
> Added Release Notes for updates before file was added.

- README.rst
Found I needed these on a fresh Ubuntu box
> Doc linux req

- CMake/External_GTest.cmake
- CMake/fletch-tarballs.cmake
- Patches/GTest/Patch.cmake
- Patches/GTest/googlemock/CMakeLists.txt
- Patches/GTest/googletest/CMakeLists.txt
EWISOTT. Includes google/googletest#1160.
> Add Google Test 1.8.0

- CMake/External_Qt.cmake
- Doc/release-notes/release.txt
This exact change by @dstoup  has already landed in `master`, but it looks like it should go in `release` too, so I back-ported it and added a release note.
> Updated MSVC2017 version

- CMakeLists.txt
Use the cuda FindCUDA finds
Allow user to change it
Made sure kwiver uses the same CUDA if changed
> Cuda support

- Patches/Boost/1.65.1/Patch.cmake
- Patches/Boost/1.65.1/add_path.cpp
- Patches/Boost/1.65.1/copy_path.cpp
This patch is only being applied to Boost 1.65.1
> Patch boost file copy

- CMake/External_GDAL.cmake
Jasper needs to be explicitly disabled on some platforms.
> Disable jasper

- CMake/fletch-tarballs.cmake
This branch is not to merge. I am testing a dashboards issue.
> Test make postgis experimental

- Patches/Qt/Patch.cmake
- Patches/Qt/messagemodel.cpp
This pull addresses #269. The patch mirrors what was done at some point in Qt 5.
https://github.com/qt/qttools/commit/7138c963f9d1258bc1b49cb4d63c3e2b7d0ccfda#diff-d0095bdb451798c994b415c042b7b246
> Patch to fix clang issues on MacOS

- Patches/OpenCV/3.1.0/Patch.cmake
Added paren that got deleted when fixing a merge conflict.
> Fix result of a bad merge conflict

- CMake/External_PNG.cmake
- CMake/External_libtiff.cmake
- CMake/External_openjpeg.cmake
- CMake/fletch-tarballs.cmake
OpenJPEG is missing possibly fletch built deps of libtiff and PNG.
> Pass deps to openjpeg

- README.rst
> [README.rst] Tiny typography

- CMake/External_GDAL.cmake
> Export fletch_ENABLED_GDAL

- CMake/fletch-tarballs.cmake
This change will make PostGIS build when 'Enable_ALL*' is set.
> Remove PostGIS from experimental list

- CMake/External_Qt.cmake
- CMake/External_qtExtensions.cmake
- CMake/Utils.cmake
- CMake/fletch-tarballs.cmake
This updates qtExtensions to the latest version and makes the necessary changes to build it against Qt5.  See commit log for details.
> Update qtExtensions, improve Qt5 support

- CMake/External_VTK.cmake
Tweak how VTK is built to support building against Qt5, when that is selected.
@dstoup, @sankhesh, PTAL.
> Add Qt5 support for VTK

- CMake/External_Caffe.cmake
> Fixes an error in set command when variable helpstring is empty.

- Patches/GDAL/1.11.5/Patch.cmake
- Patches/GDAL/1.11.5/frmts/wms/gdalwmsdataset.cpp
Use the GDAL 2.3.0 version of this file to identify the fix for a build error where GDAL is comparing a pointer to an int.
> Fix gdal1 pointer cmp

- dockerfile
Also updates the version of cmake and ubuntu that we build against. It might be worth migrating the base image to an nvidia one.
> update dockerfile to support remote builds

- CMake/External_PDAL.cmake
Macos also needs help finding some of these libraries, not just WIN32.
> Help PDAL find dependencies on macos

- CMake/External_GDAL.cmake
This branch does nothing other than fix bad formatting in the GDAL cmake file. Will await dashboards but then merge quickly.
> Fix confusing formatting in External GDAL cmake file

- CMake/External_VTK.cmake
Cherry-pick #563 and fix merge conflict.
> VIAME: cherry-pick disable vtk python option

- Patches/YAMLcpp/Patch.cmake
- Patches/YAMLcpp/src/node_data.cpp
Add a missing Boost header. It isn't required for Fletch's current version of Boost but will be required as we update Boost.
> Patch yaml boost 172

- CMake/External_Qt.cmake
- Patches/Eigen/Patch.cmake
- Patches/Eigen/src/LU/arch/Inverse_SSE.h
Fixes a couple of issues found on OSX 10.15
> Fix mac fixes

- CMake/External_FFmpeg.cmake
> fix ffmpeg build

- CMake/External_ZLib.cmake
- Patches/ZLib/CMakeLists.txt
- Patches/ZLib/Patch.cmake
Patch ZLib to remove the 'd' postfix on the library name in WIN32.
> Patch zlib libname

- Patches/Qt/5.12.8/Patch.cmake
- Patches/Qt/5.12.8/qtconnectivity/src/bluetooth/qbluetoothservicediscoveryagent_winrt.cpp
This is the same patch we used on Qt 5.11 to fix a build issue in the bluetooth module
> Patch Qt 5.12 for MSVC

- Patches/Darknet/Patch.cmake
- Patches/Darknet/utils.c
Two of the *nix headers are required to build on Mac as well.
> Patch darknet mac include

- CMake/External_OpenCV.cmake
- CMake/fletch-tarballs.cmake
- Doc/release-notes/master.txt
Adding option to OpenCV to use source from PyPI for version 4.5.1.
> Add option to get OpenCV source from PyPI

- Doc/release-notes/master.txt
This PR is a cumulative update to the release notes of all the development done since v1.5.0.
> Update release notes

- Patches/FFmpeg/5.1.2/Patch.cmake
- Patches/FFmpeg/5.1.2/hwcontext_vulkan.c
This PR removes some lines that prevent compilation on some machines with recent changes to the Vulkan API. See https://github.com/FFmpeg/FFmpeg/commit/eb0455d646
> Adapt FFmpeg to changing Vulkan API

- CMake/External_FFmpeg.cmake
- CMake/External_msys2.cmake
Convert to something that MSYS2 understands natively.
---
Cc: @chetnieter
> msys2: support `fletch_BUILD_INSTALL_PREFIX` with Windows slashes

- README.rst
A minor README update that clarifies what "building fletch" means.
Resolves #750
> Clarify what building Fletch means

- CMake/External_CPython.cmake
- CMake/External_OpenCV.cmake
Goal :
Fix fletch/python bugs for release generation 
Changes :
- Fix:
- Fix python include path
- Remove installation of python packages
The changed above are tested to build successfully on ubuntu 22.
> [fix] Fix python include path and remove python packages
